Update build_fe

diff --git a/build_fe b/build_fe
--- a/build_fe
+++ b/build_fe
@@ -14,9 +14,8 @@ CLILIBS='ui.apps/src/main/content/jcr_root/apps/'
 
 main() {
 	# check for aemsync and nvm  
-	. ~/.nvm/nvm.sh >/dev/null
 	type aemsync &>/dev/null || { echo "aemsync is required, but it's not installed. Aborting."; exit 1; }
-	command -v nvm >/dev/null || { echo "nvm is required, but it's not installed.  Aborting."; exit 1; }
+	{ . ~/.nvm/nvm.sh; command -v nvm >/dev/null } || { echo "nvm is required, but it's not installed.  Aborting."; exit 1; }
 	
 	# print usage if no cmd line args
 	if [ "$#" -eq 0  ]; then
@@ -55,35 +54,35 @@ main() {
 }
 
 build_btd() {
-	. ~/.nvm/nvm.sh
 	echo '[+] building BTD';
+	. ~/.nvm/nvm.sh
 	(cd $BTD/ui.frontend/; nvm use 12; npm run dev && echo 'done';)
 	(cd $BTD/$CLILIBS/buffalotracedistillery/clientlibs/; aemsync -t http://admin:admin@localhost:4502 -p clientlib-site/;)
 }
 
 build_bost() {
-	. ~/.nvm/nvm.sh
 	echo '[+] building mrboston';
+	. ~/.nvm/nvm.sh
 	(cd $BOST/ui.frontend/; nvm use 12; npm run dev && echo 'done';)
 	(cd $BOST/$CLILIBS/mrboston/clientlibs/; aemsync -t http://admin:admin@localhost:4502 -p clientlib-site/;)
 }
 
 build_fb() {
+	echo '[+] building fireball';
 	. ~/.nvm/nvm.sh
-	echo '[+] building fireball'
 	(cd $FB/ui.frontend/; nvm use 12; npm run dev && echo 'done';)
 	(cd $FB/$CLILIBS/fireball/clientlibs/; aemsync -t http://admin:admin@localhost:4502 -p clientlib-site/;)
 }
 
 build_cif() {
-	. ~/.nvm/nvm.sh
 	echo '[+] building cif react-components';
+	. ~/.nvm/nvm.sh
 	(cd $SCC/react-components/; pwd; nvm use 12; npm run webpack:dev && echo 'done';)
 }
 
 build_soco() {
-	. ~/.nvm/nvm.sh >/dev/null
 	echo '[+] building soco';
+	. ~/.nvm/nvm.sh
 	(cd $SOCO/ui.frontend.soco/; nvm use 10; npm run dev && echo 'done';)
 	(cd $SOCO/$CLILIBS/sazerac-aem-blueprint/clientlibs/soco/clientlib-site-soco; aemsync -t http://admin:admin@localhost:4502 -p clientlib-site-soco/;)
 }
